// Mocks generated by Mockito 5.4.6 from annotations
// in fpt_ojt/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpt_ojt/core/common/token/token_store.dart' as _i9;
import 'package:fpt_ojt/core/storages/key_value_storage.dart' as _i10;
import 'package:fpt_ojt/features/auth/data/datasources/auth_datasource.dart'
    as _i3;
import 'package:fpt_ojt/features/auth/data/datasources/google_auth_data_source.dart'
    as _i7;
import 'package:fpt_ojt/features/auth/data/models/auth_models.dart' as _i5;
import 'package:fpt_ojt/features/auth/data/models/login_reponse.dart' as _i6;
import 'package:fpt_ojt/features/shared/models/api_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i3.AuthDataSource {
  @override
  _i4.Future<_i2.ApiResponse<_i5.TokenResponse>> loginWithEmail(
    String? email,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loginWithEmail,
              [email, password],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
              _FakeApiResponse_0<_i5.TokenResponse>(
                this,
                Invocation.method(
                  #loginWithEmail,
                  [email, password],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
                  _FakeApiResponse_0<_i5.TokenResponse>(
                    this,
                    Invocation.method(
                      #loginWithEmail,
                      [email, password],
                      {#rememberMe: rememberMe},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.TokenResponse>> loginWithGoogle(
    String? idToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, [idToken]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
              _FakeApiResponse_0<_i5.TokenResponse>(
                this,
                Invocation.method(#loginWithGoogle, [idToken]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
                  _FakeApiResponse_0<_i5.TokenResponse>(
                    this,
                    Invocation.method(#loginWithGoogle, [idToken]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>);

  @override
  _i4.Future<_i6.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i6.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.UserModel?>.value(),
          )
          as _i4.Future<_i6.UserModel?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.TokenResponse>> register({
    required String? firstName,
    required String? lastName,
    required String? username,
    required String? password,
    required String? repeatPassword,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #username: username,
              #password: password,
              #repeatPassword: repeatPassword,
              #email: email,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
              _FakeApiResponse_0<_i5.TokenResponse>(
                this,
                Invocation.method(#register, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #username: username,
                  #password: password,
                  #repeatPassword: repeatPassword,
                  #email: email,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>.value(
                  _FakeApiResponse_0<_i5.TokenResponse>(
                    this,
                    Invocation.method(#register, [], {
                      #firstName: firstName,
                      #lastName: lastName,
                      #username: username,
                      #password: password,
                      #repeatPassword: repeatPassword,
                      #email: email,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TokenResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> resetPassword(
    String? email,
    String? otp,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email, otp, newPassword]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#resetPassword, [email, otp, newPassword]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#resetPassword, [email, otp, newPassword]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);
}

/// A class which mocks [GoogleAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthDataSource extends _i1.Mock
    implements _i7.GoogleAuthDataSource {
  @override
  _i4.Future<String> getIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(this, Invocation.method(#getIdToken, [])),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(this, Invocation.method(#getIdToken, [])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i9.TokenStore {
  @override
  _i4.Future<String> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getAccessToken, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getAccessToken, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getRefreshToken, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getRefreshToken, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> saveAccessToken(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [accessToken]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(
    String? refreshToken, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveRefreshToken,
              [refreshToken],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> replaceRefreshToken(String? newRefreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#replaceRefreshToken, [newRefreshToken]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i10.KeyValueStorage {
  @override
  _i4.Future<void> set<T extends Object>(String? key, T? value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<T?> get<T extends Object>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i4.Future<T?>.value(),
            returnValueForMissingStub: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
