// Mocks generated by Mockito 5.4.6 from annotations
// in fpt_ojt/test/features/auth/presentation/blocs/login_options/login_options_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:fpt_ojt/core/error/failures.dart' as _i5;
import 'package:fpt_ojt/core/usecase/usecase_interface.dart' as _i7;
import 'package:fpt_ojt/features/auth/domain/entites/user.dart' as _i6;
import 'package:fpt_ojt/features/auth/domain/usecases/login_with_google.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginWithGoogleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithGoogleUseCase extends _i1.Mock
    implements _i2.LoginWithGoogleUseCase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);
}
