// Mocks generated by Mockito 5.4.6 from annotations
// in fpt_ojt/test/features/intro/presentation/blocs/onboarding/onboarding_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:fpt_ojt/core/error/failures.dart' as _i6;
import 'package:fpt_ojt/core/usecase/usecase_interface.dart' as _i7;
import 'package:fpt_ojt/features/intro/domain/repositories/onboarding_repository.dart'
    as _i2;
import 'package:fpt_ojt/features/intro/domain/usecases/end_onboarding.dart'
    as _i3;
import 'package:fpt_ojt/features/intro/domain/usecases/get_onboarding_completion_status.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOnboardingRepository_0 extends _i1.SmartFake
    implements _i2.OnboardingRepository {
  _FakeOnboardingRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EndOnboardingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndOnboardingUseCase extends _i1.Mock
    implements _i3.EndOnboardingUseCase {
  @override
  _i2.OnboardingRepository get onboardingRepository =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingRepository),
            returnValue: _FakeOnboardingRepository_0(
              this,
              Invocation.getter(#onboardingRepository),
            ),
            returnValueForMissingStub: _FakeOnboardingRepository_0(
              this,
              Invocation.getter(#onboardingRepository),
            ),
          )
          as _i2.OnboardingRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);
}

/// A class which mocks [GetOnboardingCompletionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnboardingCompletionStatusUseCase extends _i1.Mock
    implements _i9.GetOnboardingCompletionStatusUseCase {
  @override
  _i2.OnboardingRepository get onboardingRepository =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingRepository),
            returnValue: _FakeOnboardingRepository_0(
              this,
              Invocation.getter(#onboardingRepository),
            ),
            returnValueForMissingStub: _FakeOnboardingRepository_0(
              this,
              Invocation.getter(#onboardingRepository),
            ),
          )
          as _i2.OnboardingRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, bool>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, bool>>);
}
