// Mocks generated by Mockito 5.4.6 from annotations
// in fpt_ojt/test/features/auth/domain/usecases/login_with_email_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:fpt_ojt/core/error/failures.dart' as _i5;
import 'package:fpt_ojt/features/auth/domain/entites/user.dart' as _i6;
import 'package:fpt_ojt/features/auth/domain/repository/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> loginWithEmail(
    String? email,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loginWithEmail,
              [email, password],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(
                  #loginWithEmail,
                  [email, password],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                    this,
                    Invocation.method(
                      #loginWithEmail,
                      [email, password],
                      {#rememberMe: rememberMe},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#loginWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                    this,
                    Invocation.method(#loginWithGoogle, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#logout, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> register({
    required String? firstName,
    required String? lastName,
    required String? username,
    required String? password,
    required String? repeatPassword,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #username: username,
              #password: password,
              #repeatPassword: repeatPassword,
              #email: email,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#register, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #username: username,
                  #password: password,
                  #repeatPassword: repeatPassword,
                  #email: email,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                    this,
                    Invocation.method(#register, [], {
                      #firstName: firstName,
                      #lastName: lastName,
                      #username: username,
                      #password: password,
                      #repeatPassword: repeatPassword,
                      #email: email,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#forgotPassword, [email]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> resetPassword(
    String? email,
    String? otp,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email, otp, newPassword]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#resetPassword, [email, otp, newPassword]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#resetPassword, [
                      email,
                      otp,
                      newPassword,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
